# print("Day 1 - Python Print Function")
# print("The function is declared like this:")
# print("print('what to print')")
# print('\n')
# print("Hello world!\nHello World!\nHello World!")
# print('\n')
# print("Hello" + " Bryant")
# print('\n')
# print("Day 1 - String Manipulation")
# print("String Concatention is done with the '+' sign")
# print('e.g. print("Hello" + "World")')
# print("New lines can be created with a blackslash and n")
# print('\n')
# print("\n")
# print("Hello " + input("What is your name?"))
# #this is a comment
# print('\n')
# print("\n")
# name = input("What is your name?")
# nameLength = len(name)
# print(nameLength)
# #print(len(input("What is your name?")))
# print('\n')
# a = input("a: ")
# b = input("b: ")
# c = b
# b = a
# a = c
# print("a: " + a)
# print("b: " + b)
# python variable naming ( case sensitive, camel case works, or underscoring, normal naming convetions)
print("Band Name Generator")
city = input("What city did you grew up in?")
pet_name = input("What is the name of your first pet?")
print("\nYour band name is: " + city + " " + pet_name)